### ISSUE TITLE
Invalid client ID

### ISSUE THREAD

**Issue by ghost** [Yowai-dev/PS3-Discord#7]
```
Traceback (most recent call last):
  File "/home/user/PSCord/ps3.py", line 97, in <module>
    RPC.connect()
  File "/home/user/.local/lib/python3.10/site-packages/pypresence/presence.py", line 45, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 121, in handshake
    raise DiscordError(data['code'], data['message'])
pypresence.exceptions.DiscordError: Error Code: 4000 Message: Invalid Client ID
```

getting this error on Pop!_OS 22.04

**Comment by inthecatsdreams** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/user/PSCord/ps3.py", line 97, in <module>
>     RPC.connect()
>   File "/home/user/.local/lib/python3.10/site-packages/pypresence/presence.py", line 45, in connect
>     self.loop.run_until_complete(self.handshake())
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/home/user/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 121, in handshake
>     raise DiscordError(data['code'], data['message'])
> pypresence.exceptions.DiscordError: Error Code: 4000 Message: Invalid Client ID
> ```
> 
> getting this error on Pop!_OS 22.04

[Latest commit](https://github.com/inthecatsdreams/PS3-Discord/commit/693049547030a36aa11ca2785337d5fd9bfafc05) fixed it.
